version: '3'

services:
  php:
    build: ./containers/php
    volumes:
      - ./service:/var/www
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - 13080:80
    volumes:
      - ./service:/var/www
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./containers/db/data:/var/lib/mysql
      - ./containers/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./containers/db/sql:/docker-entrypoint-initdb.d
